/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicLeadsCaptureSubmitRouteImport } from './routes/api/public/leads-capture-submit'
import { Route as ApiPublicLeadsCaptureRouteImport } from './routes/api.public.leads-capture'
import { Route as AuthenticatedAppTasksIndexRouteImport } from './routes/_authenticated/app.tasks.index'
import { Route as AuthenticatedAppPipelineIndexRouteImport } from './routes/_authenticated/app.pipeline.index'
import { Route as AuthenticatedAppLeadsIndexRouteImport } from './routes/_authenticated/app.leads.index'
import { Route as AuthenticatedAppDealsIndexRouteImport } from './routes/_authenticated/app.deals.index'
import { Route as AuthenticatedAppContactsIndexRouteImport } from './routes/_authenticated/app.contacts.index'
import { Route as AuthenticatedAppCompaniesIndexRouteImport } from './routes/_authenticated/app.companies.index'
import { Route as AuthenticatedAppActivitiesIndexRouteImport } from './routes/_authenticated/app.activities.index'
import { Route as AuthenticatedAppLeadsIdRouteImport } from './routes/_authenticated/app.leads.$id'
import { Route as AuthenticatedAppDealsIdRouteImport } from './routes/_authenticated/app.deals.$id'
import { Route as AuthenticatedAppContactsIdRouteImport } from './routes/_authenticated/app.contacts.$id'
import { Route as AuthenticatedAppCompaniesIdRouteImport } from './routes/_authenticated/app.companies.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicLeadsCaptureSubmitRoute =
  ApiPublicLeadsCaptureSubmitRouteImport.update({
    id: '/api/public/leads-capture-submit',
    path: '/api/public/leads-capture-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsCaptureRoute = ApiPublicLeadsCaptureRouteImport.update({
  id: '/api/public/leads-capture',
  path: '/api/public/leads-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTasksIndexRoute =
  AuthenticatedAppTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPipelineIndexRoute =
  AuthenticatedAppPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsIndexRoute =
  AuthenticatedAppLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsIndexRoute =
  AuthenticatedAppDealsIndexRouteImport.update({
    id: '/deals/',
    path: '/deals/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContactsIndexRoute =
  AuthenticatedAppContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompaniesIndexRoute =
  AuthenticatedAppCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActivitiesIndexRoute =
  AuthenticatedAppActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsIdRoute = AuthenticatedAppLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDealsIdRoute = AuthenticatedAppDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContactsIdRoute =
  AuthenticatedAppContactsIdRouteImport.update({
    id: '/contacts/$id',
    path: '/contacts/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompaniesIdRoute =
  AuthenticatedAppCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/public/leads-capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/leads-capture-submit': typeof ApiPublicLeadsCaptureSubmitRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/companies/$id': typeof AuthenticatedAppCompaniesIdRoute
  '/app/contacts/$id': typeof AuthenticatedAppContactsIdRoute
  '/app/deals/$id': typeof AuthenticatedAppDealsIdRoute
  '/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/app/activities/': typeof AuthenticatedAppActivitiesIndexRoute
  '/app/companies/': typeof AuthenticatedAppCompaniesIndexRoute
  '/app/contacts/': typeof AuthenticatedAppContactsIndexRoute
  '/app/deals/': typeof AuthenticatedAppDealsIndexRoute
  '/app/leads/': typeof AuthenticatedAppLeadsIndexRoute
  '/app/pipeline/': typeof AuthenticatedAppPipelineIndexRoute
  '/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/leads-capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/leads-capture-submit': typeof ApiPublicLeadsCaptureSubmitRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/companies/$id': typeof AuthenticatedAppCompaniesIdRoute
  '/app/contacts/$id': typeof AuthenticatedAppContactsIdRoute
  '/app/deals/$id': typeof AuthenticatedAppDealsIdRoute
  '/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/app/activities': typeof AuthenticatedAppActivitiesIndexRoute
  '/app/companies': typeof AuthenticatedAppCompaniesIndexRoute
  '/app/contacts': typeof AuthenticatedAppContactsIndexRoute
  '/app/deals': typeof AuthenticatedAppDealsIndexRoute
  '/app/leads': typeof AuthenticatedAppLeadsIndexRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineIndexRoute
  '/app/tasks': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/public/leads-capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/leads-capture-submit': typeof ApiPublicLeadsCaptureSubmitRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/companies/$id': typeof AuthenticatedAppCompaniesIdRoute
  '/_authenticated/app/contacts/$id': typeof AuthenticatedAppContactsIdRoute
  '/_authenticated/app/deals/$id': typeof AuthenticatedAppDealsIdRoute
  '/_authenticated/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/_authenticated/app/activities/': typeof AuthenticatedAppActivitiesIndexRoute
  '/_authenticated/app/companies/': typeof AuthenticatedAppCompaniesIndexRoute
  '/_authenticated/app/contacts/': typeof AuthenticatedAppContactsIndexRoute
  '/_authenticated/app/deals/': typeof AuthenticatedAppDealsIndexRoute
  '/_authenticated/app/leads/': typeof AuthenticatedAppLeadsIndexRoute
  '/_authenticated/app/pipeline/': typeof AuthenticatedAppPipelineIndexRoute
  '/_authenticated/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/api/public/leads-capture'
    | '/api/public/leads-capture-submit'
    | '/app/'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/leads/$id'
    | '/app/activities/'
    | '/app/companies/'
    | '/app/contacts/'
    | '/app/deals/'
    | '/app/leads/'
    | '/app/pipeline/'
    | '/app/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api/public/leads-capture'
    | '/api/public/leads-capture-submit'
    | '/app'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/leads/$id'
    | '/app/activities'
    | '/app/companies'
    | '/app/contacts'
    | '/app/deals'
    | '/app/leads'
    | '/app/pipeline'
    | '/app/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/api/public/leads-capture'
    | '/api/public/leads-capture-submit'
    | '/_authenticated/app/'
    | '/_authenticated/app/companies/$id'
    | '/_authenticated/app/contacts/$id'
    | '/_authenticated/app/deals/$id'
    | '/_authenticated/app/leads/$id'
    | '/_authenticated/app/activities/'
    | '/_authenticated/app/companies/'
    | '/_authenticated/app/contacts/'
    | '/_authenticated/app/deals/'
    | '/_authenticated/app/leads/'
    | '/_authenticated/app/pipeline/'
    | '/_authenticated/app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicLeadsCaptureRoute: typeof ApiPublicLeadsCaptureRoute
  ApiPublicLeadsCaptureSubmitRoute: typeof ApiPublicLeadsCaptureSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/leads-capture-submit': {
      id: '/api/public/leads-capture-submit'
      path: '/api/public/leads-capture-submit'
      fullPath: '/api/public/leads-capture-submit'
      preLoaderRoute: typeof ApiPublicLeadsCaptureSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads-capture': {
      id: '/api/public/leads-capture'
      path: '/api/public/leads-capture'
      fullPath: '/api/public/leads-capture'
      preLoaderRoute: typeof ApiPublicLeadsCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/tasks/': {
      id: '/_authenticated/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pipeline/': {
      id: '/_authenticated/app/pipeline/'
      path: '/pipeline'
      fullPath: '/app/pipeline/'
      preLoaderRoute: typeof AuthenticatedAppPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads/': {
      id: '/_authenticated/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AuthenticatedAppLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/': {
      id: '/_authenticated/app/deals/'
      path: '/deals'
      fullPath: '/app/deals/'
      preLoaderRoute: typeof AuthenticatedAppDealsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts/': {
      id: '/_authenticated/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AuthenticatedAppContactsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/companies/': {
      id: '/_authenticated/app/companies/'
      path: '/companies'
      fullPath: '/app/companies/'
      preLoaderRoute: typeof AuthenticatedAppCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activities/': {
      id: '/_authenticated/app/activities/'
      path: '/activities'
      fullPath: '/app/activities/'
      preLoaderRoute: typeof AuthenticatedAppActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads/$id': {
      id: '/_authenticated/app/leads/$id'
      path: '/leads/$id'
      fullPath: '/app/leads/$id'
      preLoaderRoute: typeof AuthenticatedAppLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/$id': {
      id: '/_authenticated/app/deals/$id'
      path: '/deals/$id'
      fullPath: '/app/deals/$id'
      preLoaderRoute: typeof AuthenticatedAppDealsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts/$id': {
      id: '/_authenticated/app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/app/contacts/$id'
      preLoaderRoute: typeof AuthenticatedAppContactsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/companies/$id': {
      id: '/_authenticated/app/companies/$id'
      path: '/companies/$id'
      fullPath: '/app/companies/$id'
      preLoaderRoute: typeof AuthenticatedAppCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCompaniesIdRoute: typeof AuthenticatedAppCompaniesIdRoute
  AuthenticatedAppContactsIdRoute: typeof AuthenticatedAppContactsIdRoute
  AuthenticatedAppDealsIdRoute: typeof AuthenticatedAppDealsIdRoute
  AuthenticatedAppLeadsIdRoute: typeof AuthenticatedAppLeadsIdRoute
  AuthenticatedAppActivitiesIndexRoute: typeof AuthenticatedAppActivitiesIndexRoute
  AuthenticatedAppCompaniesIndexRoute: typeof AuthenticatedAppCompaniesIndexRoute
  AuthenticatedAppContactsIndexRoute: typeof AuthenticatedAppContactsIndexRoute
  AuthenticatedAppDealsIndexRoute: typeof AuthenticatedAppDealsIndexRoute
  AuthenticatedAppLeadsIndexRoute: typeof AuthenticatedAppLeadsIndexRoute
  AuthenticatedAppPipelineIndexRoute: typeof AuthenticatedAppPipelineIndexRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCompaniesIdRoute: AuthenticatedAppCompaniesIdRoute,
  AuthenticatedAppContactsIdRoute: AuthenticatedAppContactsIdRoute,
  AuthenticatedAppDealsIdRoute: AuthenticatedAppDealsIdRoute,
  AuthenticatedAppLeadsIdRoute: AuthenticatedAppLeadsIdRoute,
  AuthenticatedAppActivitiesIndexRoute: AuthenticatedAppActivitiesIndexRoute,
  AuthenticatedAppCompaniesIndexRoute: AuthenticatedAppCompaniesIndexRoute,
  AuthenticatedAppContactsIndexRoute: AuthenticatedAppContactsIndexRoute,
  AuthenticatedAppDealsIndexRoute: AuthenticatedAppDealsIndexRoute,
  AuthenticatedAppLeadsIndexRoute: AuthenticatedAppLeadsIndexRoute,
  AuthenticatedAppPipelineIndexRoute: AuthenticatedAppPipelineIndexRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicLeadsCaptureRoute: ApiPublicLeadsCaptureRoute,
  ApiPublicLeadsCaptureSubmitRoute: ApiPublicLeadsCaptureSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
